* Personal improvement and Chambo Education tracking 
I put it on web, what a shame if I failed it.

** Time plan:
- 06:00 - 08:00: Morning study time
- 19:00 - 21:00: Play and teach Chambo
- 21:00 - 21:30: workout
- 22:00 - 23:30: Night study time
Every day 3.5h study, 0.5h workout, 2h at least for Chambo.

** Target:
1) Python
2) Machine learning
3) English reading&writing
4) Emacs & org-mode

** tracking table
| date             | 06:00-08:00 | 19:00-21:00 | 21:00-21:30   | 22:00-23:30 |
|------------------+-------------+-------------+---------------+-------------|
| <2018-05-08 Tue> | Done well   | Not so good | Bad           | Done well   |
| <2018-05-09 Wed> | Done well   | Not so good | Dumbbell work | Bad         |
| <2018-05-10 Thu> | Done well   | not so good | No            | No          |
| <2018-05-11 Fri> |             |             |               |             |



** log
*** <2018-05-07 Mon> cloudy
move the paper diary to org. Read Emacs Mini Guide.
*** <2018-05-08 Tue> cloudy to sunny
Install a github desktop to my working Windows, it's so cool and how am I get it so late!
To get my wasted 10 years back. Pretend I'm back to graduated students lab. Study python and machine learning this year. And improve English level as well. Meanwhile, must make sure 7h sleep per day, with high quality, 23:30-06:00 and 13:00-13:30.
*** <2018-05-09 Wed> Sunny
What a busy day. No time for study in the working time.
In the morning, read think python. In the Night study time, it's really too sleapy, go to bed before 11:00. lost about 1 hour.
Play electric piano, read book with Chambo, but not so good.
*** <2018-05-10 Thu> Sunny
Weihua will leave HP to Philips, have lunch with her in Huizhi.
Too sleepy this night, get sleep in the sofa about 8:00 PM, so the planed work failed.
the first 3 days, morning work are good, but night work need improve.
