* Personal improvement and Chambo Education tracking 
I put it on web, what a shame if I failed it.

** Time plan:
- 06:00 - 08:00: Morning study time
- 19:00 - 21:00: Play and teach Chambo
- 21:00 - 21:30: workout
- 22:00 - 23:30: Night study time
Every day 3.5h study, 0.5h workout, 2h at least for Chambo.

** Target:
1) Python
2) Machine learning
3) English reading&writing
4) Emacs & org-mode

** tracking table
| date             | 06:00-08:00 | 19:00-21:00 | 21:00-21:30   | 22:00-23:30 |
|------------------+-------------+-------------+---------------+-------------|
| <2018-05-08 Tue> | Done well   | Not so good | Bad           | Done well   |
| <2018-05-09 Wed> | Done well   | Not so good | Dumbbell work | Bad         |
| <2018-05-10 Thu> | Done well   | not so good | No            | No          |
| <2018-05-11 Fri> |             |             |               |             |
| <2018-05-15 Tue> | to airport  | good        | no            | Done well   |
| <2018-05-16 Wed> | to company  | good        | no            | good        |


** log
*** <2018-05-07 Mon> cloudy
move the paper diary to org. Read Emacs Mini Guide.
*** <2018-05-08 Tue> cloudy to sunny
Install a github desktop to my working Windows, it's so cool and how am I get it so late!
To get my wasted 10 years back. Pretend I'm back to graduated students lab. Study python and machine learning this year. And improve English level as well. Meanwhile, must make sure 7h sleep per day, with high quality, 23:30-06:00 and 13:00-13:30.
*** <2018-05-09 Wed> Sunny
What a busy day. No time for study in the working time.
In the morning, read think python. In the Night study time, it's really too sleapy, go to bed before 11:00. lost about 1 hour.
Play electric piano, read book with Chambo, but not so good.
*** <2018-05-10 Thu> Sunny
Weihua will leave HP to Philips, have lunch with her in Huizhi.
Too sleepy this night, get sleep in the sofa about 8:00 PM, so the planed work failed.
the first 3 days, morning work are good, but night work need improve.
*** <2018-05-15 Tue> sunny
Drive to take M to Airport in the morning. And goto two gas station with no gas supply. There's oil only for 40km when I get the office. In 5:00, I back home, waiting a long line in a Sinopec gas station and final only get 50RMB oil to avoid the car stop on the way to Petro station. When I finally get the Petro station, I found the oil card is missing, can't find it anywhere. then I have to go home with only 50RMB oil. and in home, I find the card is actually in my wallet. What a mess.
First time I take Chambo a shower. Will do it every day from now on.
Studying install os in virtual box these two days. ok in win10, but failed in ubuntu.
*** <2018-05-16 Wed> sunny
have a meeting 8:00AM. go to office @7:00am, so only 1hr for morning study.
finished /Think Python/ study.
